sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDoAxfM4rHWBGKbrL56
    access-key-secret: BnUCqqaRtxs7x46ZeVDPZRWvGmzAyT
    bucket-name: sky-take-super
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx4f1ea9a66a72dee9
    secret: 0ea088587936e580b947f2d02375be55
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl:  https://74c29b84.r8.cpolar.top/notify/paySuccess
    refundNotifyUrl:  https://74c29b84.r8.cpolar.top/notify/refundSuccess